### PR TITLE
[ceremonies] don't create assignment when less than 3 participan…

### LINKED ISSUE #103: meetup can happen with only one participant.
Probably, this only happens if only one participant is registered for the whole CommunityCeremony.

### PR DESCRIPTION
**Pull request by NicJak**
* Closes #103

### CODE REVIEW

**Review by brenzi — CHANGES_REQUESTED** [review]
Please add a unit test to see assignment of 2 participants rejected

**Review by brenzi — APPROVED** [review]

**Comment by NicJak** [comment]
since you approved the change: have you checked for this fix to be enough or should I proceed with some heuristic testing?

**Comment by brenzi** [comment]
I have approved because I think the testing goes beyond this PR. Would be great if you could add parametric testing and cover a few edge cases of possible small numbers of bootstrappers, endorsees, reputabkes and newbies

**Review by clangenb — APPROVED** [review]
LGTM.

**Pull request merged**
